from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import TimeStampedModel
from django.contrib.auth import get_user_model
from projects.models import Project

User = get_user_model()

class NotificationType(models.TextChoices):
    COLLAB_REQUEST = 'COLLAB_REQUEST', _('Collaboration Request')
    MESSAGE = 'MESSAGE', _('New Message')
    NDA_APPROVED = 'NDA_APPROVED', _('NDA Approved')
    PROFILE_VERIFIED = 'PROFILE_VERIFIED', _('Profile Verified')
    SYSTEM = 'SYSTEM', _('System Notification')

class Notification(TimeStampedModel):
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    title = models.CharField(max_length=255)
    message = models.TextField()
    notification_type = models.CharField(max_length=50, choices=NotificationType.choices, default=NotificationType.SYSTEM)
    is_read = models.BooleanField(default=False)
    
    # Optional link to related object (e.g. Project ID or Message ID)
    related_object_id = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.recipient.email}"

class Conversation(TimeStampedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='conversations', null=True, blank=True)
    is_group = models.BooleanField(default=False)
    participants = models.ManyToManyField(User, through='ConversationParticipant', related_name='conversations')
    
    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        if self.is_group and self.project:
            return f"{self.project.title} || Group Chat"
        return f"Conversation {self.id}"

class ConversationParticipant(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)
    last_read_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True, help_text="False if user left or was removed")

    class Meta:
        unique_together = ('conversation', 'user')

class MessageType(models.TextChoices):
    TEXT = 'text', _('Text')
    IMAGE = 'image', _('Image')
    VOICE = 'voice', _('Voice Note')
    SYSTEM = 'system', _('System')

class Message(TimeStampedModel):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='messages', null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages', null=True, blank=True)
    
    message_type = models.CharField(max_length=10, choices=MessageType.choices, default=MessageType.TEXT)
    content = models.TextField(blank=True) # Text can be blank if just sending an image/voice note
    media_url = models.URLField(max_length=500, null=True, blank=True)
    voice_duration = models.CharField(max_length=10, null=True, blank=True, help_text="e.g. 0:42")
    
    is_ai_generated = models.BooleanField(default=False, help_text="True if this message was generated by VentureAI")

    class Meta:
        ordering = ['created_at'] # Oldest first for chat history

    def __str__(self):
        return f"Message from {self.sender.email} in {self.conversation}"

class FCMDevice(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fcm_devices')
    token = models.CharField(max_length=255, unique=True, help_text="Firebase Cloud Messaging token")
    device_name = models.CharField(max_length=100, blank=True, null=True, help_text="e.g. iPhone 14 Pro, Pixel 7")
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.user.email} - {self.device_name}"

