from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import TimeStampedModel
from django.contrib.auth import get_user_model
from projects.models import Project

User = get_user_model()

class NotificationType(models.TextChoices):
    COLLAB_REQUEST = 'COLLAB_REQUEST', _('Collaboration Request')
    MESSAGE = 'MESSAGE', _('New Message')
    NDA_APPROVED = 'NDA_APPROVED', _('NDA Approved')
    PROFILE_VERIFIED = 'PROFILE_VERIFIED', _('Profile Verified')
    SYSTEM = 'SYSTEM', _('System Notification')

class Notification(TimeStampedModel):
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    title = models.CharField(max_length=255)
    message = models.TextField()
    notification_type = models.CharField(max_length=50, choices=NotificationType.choices, default=NotificationType.SYSTEM)
    is_read = models.BooleanField(default=False)
    
    # Optional link to related object (e.g. Project ID or Message ID)
    related_object_id = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.recipient.email}"

class Conversation(TimeStampedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='conversations', null=True, blank=True)
    is_group = models.BooleanField(default=False)
    participants = models.ManyToManyField(User, through='ConversationParticipant', related_name='conversations')
    
    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        if self.is_group and self.project:
            return f"{self.project.title} || Group Chat"
        return f"Conversation {self.id}"

class ConversationParticipant(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)
    last_read_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('conversation', 'user')

class Message(TimeStampedModel):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='messages', null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    content = models.TextField()
    is_ai_generated = models.BooleanField(default=False, help_text="True if this message was generated by VentureAI")

    class Meta:
        ordering = ['created_at'] # Oldest first for chat history

    def __str__(self):
        return f"Message from {self.sender.email} in {self.conversation}"

