# Generated by Django 6.1 on 2026-09-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_savedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
