# Generated by Django 6.1 on 2026-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_sponsorprofile_bio_sponsorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('NONE', 'None')], db_index=True, default='NONE', max_length=20),
        ),
    ]
