# Generated by Django 6.1 on 2026-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_sponsorprofile_sponsor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='company_website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='legal_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
