# Generated by Django 6.1 on 2026-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_investorprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='nda_confidentiality_terms',
            field=models.TextField(blank=True, default='This Non-Disclosure Agreement governs the disclosure of confidential and proprietary information between the parties. By signing below, you agree to keep all disclosed materials strictly confidential and use them solely for evaluation purposes.'),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='nda_custom_clauses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='nda_pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='sponsor_ndas/'),
        ),
    ]
