# Generated by Django 6.1 on 2026-09-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('short_description', models.TextField(help_text='A brief summary of the project.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FUNDED', 'Funded'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Total amount to raise', max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('minimum_investment', models.DecimalField(decimal_places=2, help_text='Minimum Investment Amount (MIA)', max_digits=12)),
                ('target_roi', models.DecimalField(decimal_places=2, help_text='Target ROI percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('timeline_months', models.PositiveIntegerField(help_text='Project timeline in months')),
                ('business_description', models.TextField(blank=True)),
                ('current_status', models.TextField(blank=True, verbose_name="What's Happening Now")),
                ('next_milestones', models.TextField(blank=True)),
                ('use_of_funds', models.TextField(blank=True)),
                ('skin_in_the_game', models.DecimalField(decimal_places=2, default=0.0, help_text="Sponsor's invested amount", max_digits=12)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='projects.category')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.sponsorprofile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('is_confidential', models.BooleanField(default=False, help_text='Requires NDA to view')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Team Member',
                'verbose_name_plural': 'Project Team Members',
            },
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposal_text', models.TextField(blank=True, help_text='Message from the investor')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed')], db_index=True, default='PENDING', max_length=20)),
                ('nda_signed', models.BooleanField(default=False, help_text='Has the investor signed the NDA for this project?')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='profiles.investorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='projects.project')),
            ],
            options={
                'verbose_name': 'Collaboration Request',
                'verbose_name_plural': 'Collaboration Requests',
                'unique_together': {('project', 'investor')},
            },
        ),
    ]
