# Generated by Django 6.1 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='nda_digital_signature',
            field=models.CharField(blank=True, help_text='Typed full name for NDA signature', max_length=255),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='nda_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='nda_signatures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='hold_period_months',
            field=models.PositiveIntegerField(blank=True, help_text='Hold period in months', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='potential_monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline_to_operations_months',
            field=models.PositiveIntegerField(blank=True, help_text='Timeline to operations in months', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='timeline_months',
            field=models.PositiveIntegerField(help_text='Overall project timeline in months'),
        ),
    ]
