# Generated by Django 6.1 on 2026-09-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('projects', '0002_collaborationrequest_nda_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confidentiality_agreement_text',
            field=models.TextField(blank=True, help_text='Detailed explanation of the confidentiality agreement'),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_stage',
            field=models.CharField(blank=True, help_text='e.g. Seed, Series A', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profiles.industry'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members_text',
            field=models.CharField(blank=True, help_text='Names, comma separated', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_description',
            field=models.TextField(blank=True, help_text='Full Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='e.g. Austin, TX', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='One-line pitch', max_length=120),
        ),
    ]
