# Generated by Django 6.1 on 2026-10-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status_savedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
