# Generated by Django 6.1 on 2026-10-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('bg_gradient_start', models.CharField(default='#0F1E2E', max_length=7)),
                ('bg_gradient_end', models.CharField(default='#162A3D', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('target_project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, help_text='Target role (e.g., INVESTOR). Blank for all.', max_length=20)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
