# Generated by Django 6.1 on 2026-09-02 03:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=authentication.models._generate_otp_code, max_length=6)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=20)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
            },
        ),
    ]
