# Generated by Django 6.1 on 2026-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice Note')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.CharField(blank=True, help_text='e.g. 0:42', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
